name: Tag on Merge to Main

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TAG_PUSH }} # PAT so tag push triggers release-on-tag

      - name: Setup Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Generate changelog BEFORE bump so it covers commits since last tag
      - name: Generate changelog text
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude_types: other,perf

      - name: Determine and bump version (commit + tag)
        id: bump
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
          NEW_VERSION="$major.$minor.$((patch+1))"
          npm version "$NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Prepend to CHANGELOG.md
        run: |
          NEW_CHANGELOG="## v${{ steps.bump.outputs.new_version }}\n\n${{ steps.changelog.outputs.changelog }}\n"
          if [ -f CHANGELOG.md ]; then
            cp CHANGELOG.md OLD_CHANGELOG.md
            echo -e "$NEW_CHANGELOG\n$(cat OLD_CHANGELOG.md)" > CHANGELOG.md
          else
            echo -e "$NEW_CHANGELOG" > CHANGELOG.md
          fi

      - name: Amend commit to include CHANGELOG.md
        run: |
          git add CHANGELOG.md
          git commit --amend --no-edit

      - name: Push commit and tag
        run: git push origin main --follow-tags
