name: Tag on Merge to Main

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TAG_PUSH }}  # Use PAT so tag push triggers release-on-tag

      - name: Setup Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Determine next version
        id: bump
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
          NEW_VERSION="$major.$minor.$((patch+1))"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      # ✅ npm will bump, commit, and tag in one step
      - name: Bump version and tag
        run: npm version ${{ steps.bump.outputs.new_version }}

      - name: Push commit and tag
        run: git push origin main --follow-tags
